/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package importadados;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;

/**
 *
 * @author cg3018211
 */
public class Interface extends javax.swing.JFrame {
    public static int cont = 0;
    public static ArrayList<Cadastro> bd = new ArrayList<Cadastro>();
    String arqLeitura = "dados_ordenados.txt";
    /**
     * Creates new form ASFAAF
     */
    public Interface(ArrayList<Cadastro> x) {
        initComponents();
        this.bd = x;
        
        Atualiza();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dispNome = new javax.swing.JTextField();
        LNome = new javax.swing.JLabel();
        LCpf = new javax.swing.JLabel();
        LDataNasc = new javax.swing.JLabel();
        dispCPF = new javax.swing.JTextField();
        dispData = new javax.swing.JTextField();
        LEnd = new javax.swing.JLabel();
        dispEnd = new javax.swing.JTextField();
        LNum = new javax.swing.JLabel();
        dispNum = new javax.swing.JTextField();
        LCidade = new javax.swing.JLabel();
        dispCidade = new javax.swing.JTextField();
        LEst = new javax.swing.JLabel();
        dispEstado = new javax.swing.JTextField();
        btProx = new javax.swing.JButton();
        btAnt = new javax.swing.JButton();
        btExcluir = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        btInserir = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        buscarLabel = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        contTotal = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jLabel4.setText("jLabel4");

        jLabel8.setText("jLabel8");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LNome.setText("Nome");

        LCpf.setText("CPF");

        LDataNasc.setText("Data Nascimento");

        LEnd.setText("Endereço");

        LNum.setText("Numero");

        LCidade.setText("Cidade");

        LEst.setText("Estado");

        btProx.setText("Proximo");
        btProx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                proximoClicked(evt);
            }
        });

        btAnt.setText("Anterior");
        btAnt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorClicked(evt);
            }
        });

        btExcluir.setText("Excluir");
        btExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirClicked(evt);
            }
        });

        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limparClicked(evt);
            }
        });

        btInserir.setText("Inserir");
        btInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirClicked(evt);
            }
        });

        btEdit.setText("Editar");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarClicked(evt);
            }
        });

        jLabel2.setText("Buscar");

        buscarLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                buscarLabelSolta(evt);
            }
        });

        display.setColumns(20);
        display.setRows(5);
        display.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                displayClick(evt);
            }
        });
        jScrollPane1.setViewportView(display);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LNome)
                            .addComponent(LCpf)
                            .addComponent(LDataNasc, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LEnd)
                            .addComponent(LNum)
                            .addComponent(LCidade)
                            .addComponent(LEst))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(dispEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(dispCidade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dispNum, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dispEnd, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dispData, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dispCPF, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dispNome, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btAnt, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btProx, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(103, 103, 103)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE)
                            .addComponent(buscarLabel)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contTotal)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(dispNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(LNome))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LCpf)
                            .addComponent(dispCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LDataNasc)
                            .addComponent(dispData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LEnd)
                            .addComponent(dispEnd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LNum)
                            .addComponent(dispNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LCidade)
                            .addComponent(dispCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LEst)
                            .addComponent(dispEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAnt)
                    .addComponent(btProx)
                    .addComponent(btLimpar)
                    .addComponent(jLabel2)
                    .addComponent(buscarLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btInserir)
                            .addComponent(btEdit)
                            .addComponent(btExcluir)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(contTotal)))
                .addContainerGap(89, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void anteriorClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorClicked
        cont--;
        if(cont <0){
            cont = bd.size()-1;
        }
        Atualiza();
    }//GEN-LAST:event_anteriorClicked

    public void escrever_arquivo() throws IOException {

        
        BufferedWriter buffWrite = new BufferedWriter(new FileWriter("dados_novos.csv", StandardCharsets.ISO_8859_1, false));

        for (int i = 0; i < bd.size(); i++) {
            buffWrite.append(bd.get(i).toString()+"\n");
        }
          
        buffWrite.close();
    }
    private void excluirClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirClicked
         int resposta = JOptionPane.showConfirmDialog( null,"Confirma a exclusão de \n"+this.bd.get(cont).getNome(), "Exclusão de Registro",JOptionPane.YES_NO_OPTION);
        
        if(resposta == 0){
            this.bd.remove(cont);
            Atualiza();
        }  
        try {
            this.escrever_arquivo();
        } catch (IOException e) {
        }
    }//GEN-LAST:event_excluirClicked

    private void proximoClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_proximoClicked
        cont++;
        if (cont >= bd.size()){
            cont = 0;
        }
        Atualiza();
    }//GEN-LAST:event_proximoClicked

    private void limparClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limparClicked
            this.dispNome.setText("");
            this.dispCPF.setText("");
            this.dispData.setText("");
            this.dispEnd.setText("");
            this.dispNum.setText("");
            this.dispCidade.setText("");
            this.dispEstado.setText("");
    }//GEN-LAST:event_limparClicked

    private void inserirClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirClicked
            Cadastro novo = new Cadastro();
            
            novo.setNome(this.dispNome.getText());
            novo.setCpf(this.dispCPF.getText());
            novo.setData_nasc(this.dispData.getText());
            novo.setEndereco(this.dispEnd.getText());
            novo.setNumero(Integer.parseInt(this.dispNum.getText()));
            novo.setCidade(this.dispCidade.getText());
            novo.setEstado(this.dispEstado.getText());
            
            bd.add(novo);
            bd.sort(null);
            
            try {
                this.escrever_arquivo();
            } catch (IOException e){
            }
    }//GEN-LAST:event_inserirClicked

    private void editarClicked(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarClicked
            this.bd.get(cont).setNome(this.dispNome.getText());
            this.bd.get(cont).setCpf(this.dispCPF.getText());
            this.bd.get(cont).setData_nasc(this.dispData.getText());
            this.bd.get(cont).setEndereco(this.dispEnd.getText());
            this.bd.get(cont).setNumero(Integer.valueOf(this.dispNum.getText()));
            this.bd.get(cont).setCidade(this.dispCidade.getText());
            this.bd.get(cont).setEstado(this.dispEstado.getText());
            
            bd.sort(null);
            try {
                this.escrever_arquivo();
            } catch (IOException e){
            }
    }//GEN-LAST:event_editarClicked

    private void buscarLabelSolta(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_buscarLabelSolta
        this.display.setText("");
        
        for (int i = 0; i < bd.size(); i++){
            if(bd.get(i).existe(this.buscarLabel.getText()))
                this.display.append(bd.get(i).getNome()+"\n");
        }
        this.contTotal.setText(String.valueOf(this.display.getLineCount()-1)+" registros encontrados");
    }//GEN-LAST:event_buscarLabelSolta

    private void displayClick(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_displayClick
        try {
            // descubro qual linha foi clicada
            int linha = this.display.getLineOfOffset(display.getCaretPosition());
            // defino o inicio do texto dessa linha
            int inicio = display.getLineStartOffset(linha);
            // defino o final da linha
            int fim = display.getLineEndOffset(linha);
            
            //gero um string a partir a linha que foi clicada
            String s = display.getDocument().getText(inicio, fim-inicio-1);
            this.display.select(inicio, fim-1);
            
            for (int i=0; i < bd.size(); i++){
                if(bd.get(i).existe(s)){
                    cont = i;
                    this.Atualiza();
                }
            }
        } catch(BadLocationException ex) {
            Logger.getLogger(Interface.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_displayClick

    public void Atualiza(){
        if(bd.size()<=0){
            this.dispNome.setText("Nada a exibir");
            this.dispCPF.setText("Nada a exibir");
            this.dispData.setText("Nada a exibir");
            this.dispEnd.setText("Nada a exibir");
            this.dispNum.setText("Nada a exibir");
            this.dispCidade.setText("Nada a exibir");
            this.dispEstado.setText("Nada a exibir");
        } else{
        
            if(cont > bd.size()-1)
                cont = bd.size()-1;

            this.dispNome.setText(this.bd.get(cont).getNome());
            this.dispCPF.setText(this.bd.get(cont).getCpf());
            this.dispData.setText(this.bd.get(cont).getData_nasc());
            this.dispEnd.setText(this.bd.get(cont).getEndereco());
            this.dispNum.setText(String.valueOf(this.bd.get(cont).getNumero()));
            this.dispCidade.setText(this.bd.get(cont).getCidade());
            this.dispEstado.setText(this.bd.get(cont).getEstado());
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Interface.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Interface().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LCidade;
    private javax.swing.JLabel LCpf;
    private javax.swing.JLabel LDataNasc;
    private javax.swing.JLabel LEnd;
    private javax.swing.JLabel LEst;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LNum;
    private javax.swing.JButton btAnt;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btExcluir;
    private javax.swing.JButton btInserir;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btProx;
    private javax.swing.JTextField buscarLabel;
    private javax.swing.JLabel contTotal;
    private javax.swing.JTextField dispCPF;
    private javax.swing.JTextField dispCidade;
    private javax.swing.JTextField dispData;
    private javax.swing.JTextField dispEnd;
    private javax.swing.JTextField dispEstado;
    private javax.swing.JTextField dispNome;
    private javax.swing.JTextField dispNum;
    private javax.swing.JTextArea display;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
